### PR TITLE
feat/chore: Fix Education Zones to use location codes

### PR DESCRIPTION
**Pull request by zikani03**
Fixed the education zone entity to use taCode and districtCode and fixed some of the functionality of the feature including

- adding migration for the location codes
- Adding a delete page
- adding a view entity to fetch districtName and taName
- Adding javascript to toggle the location selection input controls
- Consolidating the edit and new templates
- updating the educationform class

### CODE REVIEW

**Review by kamfosica — CHANGES_REQUESTED** [review]
### Education Zones

- Alternate name required?
- Remove hard deletion or implement soft deletion or delete only when not in use or remove deletion completely

### Schools 

- Show mapped zone name under school listings

image

**Comment by kamfosica** [comment]
- School doesn't show education level name only shows code
- It also seems that the code is not unique leading to multiple schools with the same code being added. (Can be converted into an issue and be fixed later?)

image

**Comment by zikani03** [comment]
I think we can convert both these observations into separate issues
- We have to circle back on that enum/code conversation with regards to educationLevel here
- On the uniqueness of the code, have to look at the school data I had seen before to confirm that I didn't see duplicates in there.

**Review by kamfosica — APPROVED** [review]
Alright. So you can convert them into issues and merge

**Pull request merged**
